# Site settings
title: Dawn
email: theoperatore@gmail.com
description: "A basic Text Adventure Game Engine written in Java named Dawn because of the time of day it was conceived."
baseurl: "/dawn"
url: "http://anpetersen.me"
twitter_username: TheOperatore
github_username:  theoperatore

kramdown:
    input: GFM

# Build settings
markdown: kramdown
permalink: pretty


collections:
    core:
        output: true
    constructs:
        output: true
    parser:
        output: true